name: CodSpeed

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  codspeed:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: 24
          cache: yarn

      - name: Install Rust
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu

      - name: Cache cargo
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.napi-rs
            .cargo-cache
            target/
          key: x86_64-unknown-linux-gnu-cargo-ubuntu-latest-codspeed-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build native addon
        run: yarn build --target x86_64-unknown-linux-gnu --use-napi-cross

      - name: Run benchmarks
        uses: CodSpeedHQ/action@fa0c9b1770f933c1bc025c83a9b42946b102f4e6 # v4
        with:
          mode: simulation
          run: node benchmark/bench.ts
